title: "Homepage"
author: "Jaike van Twiller"
description: "Personal Webpage"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {title: "LinkedIn", url: "https://www.linkedin.com/in/jaike-van-twiller/"}
  - {title: "Pure", url: "https://pure.itu.dk/en/persons/jaike-van-twiller"}
  - {title: "Google Scholar", url: "https://scholar.google.com/citations?user=UT1nU-sAAAAJ&hl=nl"}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:jaiv@itu.dk"}
  - {title: Github, icon: github, url: "https://github.com/optimalpursuit"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
